<a href="https://colab.research.google.com/github/haceworld/TensorFlow-Developer-Certification-Course/blob/main/Section_2_27_%2628.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Finding the min, max, mean, sum (aggregation)**

You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax reduce()_[action], such as:

tf.reduce_min() - find the minimum value in a tensor.

tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).


tf.reduce_mean() - find the mean of all elements in a tensor.

tf.reduce_sum() - find the sum of all elements in a tensor.

**Note:** typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().
Let's see them in action.

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# Create a tensor with 50 random values between 0 and 100
E = tf.constant(np.random.randint(low=0, high=100, size=50))
# E = tf.constant(np.random.randint(0, 100, size=50)) # can be written this way too.
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([56, 96, 98,  8, 44, 90, 67, 64, 33, 48, 14, 99, 70, 95, 61, 52,  4,
       48, 49,  1, 32, 61, 16, 65, 58, 37, 65, 87, 45, 77, 90, 97, 12, 78,
        7, 63, 63, 22,  3, 98, 73, 45, 76, 16, 56, 55, 72, 68, 66, 63])>

In [ ]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=55>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2763>

#28. Tensor Troubleshooting example (updating tensor datatypes)

In [ ]:
#Find the variance
# tf.reduce_variance(E) # won't work ....

# To find the variance of our tensor, we need access to tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=792>

In [ ]:
#Find the variance using the tf.math.reduce

tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=792.55237>

In [ ]:
# Find the standard deviation
# tf.reduce_stddev(E) # won't work ...
# tf.math.reduce_std(E) # wont work too ...


tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.152308>

You can also find the standard deviation (tf.reduce_std()) and variance (tf.reduce_variance()) of elements in a tensor using similar methods.