<a href="https://colab.research.google.com/github/haceworld/TensorFlow-Developer-Certification-Course/blob/main/Section2_31.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**One-hot encoding**

If you have a tensor of indicies and would like to one-hot encode it, you can use tf.one_hot().

You should also specify the depth parameter (the level which you want to one-hot encode to).

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="yes!", off_value="no!")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes!', b'no!', b'no!', b'no!'],
       [b'no!', b'yes!', b'no!', b'no!'],
       [b'no!', b'no!', b'yes!', b'no!'],
       [b'no!', b'no!', b'no!', b'yes!']], dtype=object)>