<a href="https://colab.research.google.com/github/haceworld/TensorFlow-Developer-Certification-Course/blob/main/Section2_30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Squeezing a tensor (removing all single dimensions)**

If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use tf.squeeze().

tf.squeeze() - remove all dimensions of 1 from a tensor.

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int64, numpy=
array([[[[[43,  9, 52,  4, 21, 99, 95, 22, 54,  1, 84, 25, 31, 97, 47,
           78, 26, 68, 47, 54, 21, 47, 16,  6, 96, 29, 69, 96, 63, 10,
            6,  9, 79, 25, 74, 39, 79, 57, 92, 25, 19, 33,  7, 55, 21,
           31, 25, 75, 93, 94]]]]])>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G.ndim

5

In [ ]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed 

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([43,  9, 52,  4, 21, 99, 95, 22, 54,  1, 84, 25, 31, 97, 47, 78, 26,
       68, 47, 54, 21, 47, 16,  6, 96, 29, 69, 96, 63, 10,  6,  9, 79, 25,
       74, 39, 79, 57, 92, 25, 19, 33,  7, 55, 21, 31, 25, 75, 93, 94])>

In [ ]:
G_squeezed.shape

TensorShape([50])

In [ ]:
G_squeezed.ndim

1