<a href="https://colab.research.google.com/github/haceworld/TensorFlow-Developer-Certification-Course/blob/main/Section_2_15_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information frrom tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself!

In [2]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [3]:
#create with tensor with tf.constant()
scalar = tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [6]:
#create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# check the dimension of the vector
vector.ndim

1

In [8]:
# create a matrix (with more than 1 dimension)
matrix = tf.constant([[9, 9], [7, 7], [8, 8]])
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 9],
       [7, 7],
       [8, 8]], dtype=int32)>

In [9]:
#check the dimension of the matrix
matrix.ndim

2

In [13]:
# create a matrix (with more than 1 dimension)
matrix1 = tf.constant([[9, 2, 1, 9], [7, 5, 2, 7], [8, 1, 0,  8]])
matrix1


<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[9, 2, 1, 9],
       [7, 5, 2, 7],
       [8, 1, 0, 8]], dtype=int32)>

In [14]:
matrix1.ndim

2

In [23]:
#another matrix with tf.float
matrix3 = tf.constant([[10., 7.],
                       [3., 2.],
                       [8., 5.]], dtype=tf.float16) # specify the data type with float
matrix3

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  5.]], dtype=float16)>

In [24]:
matrix3.ndim

2

Note: scalar always has zero (0) dimension, vector always has one (1) dimension, and matrix has two (2) dimension.


In [15]:
#Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [3, 4, 5]],
                      [[5, 6, 7],
                       [8, 6, 9]],
                      [[2, 1, 5],
                       [5, 7, 8]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [8, 6, 9]],

       [[2, 1, 5],
        [5, 7, 8]]], dtype=int32)>

In [21]:
tensor.ndim

3

In [16]:
tensor1 = tf.constant([[[1, 2, 3],
                       [3, 4, 5]],
                      [[5, 6, 7],
                       [8, 6, 9]],
                      [[2, 1, 5],
                       [5, 7, 8]],
                      [[4, 7, 8],
                       [4, 7, 2]]])
tensor1

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [8, 6, 9]],

       [[2, 1, 5],
        [5, 7, 8]],

       [[4, 7, 8],
        [4, 7, 2]]], dtype=int32)>

In [20]:
tensor1.ndim

3

In [17]:
tensor2 = tf.constant([[[1, 2],
                       [3, 4],
                       [5, 1]],
                      [[5, 6],
                       [8, 6],
                       [7, 4]],
                      [[2, 1],
                       [5, 3],
                       [5, 7]],
                      [[5, 2],
                       [4, 8],
                       [9, 2]]])
tensor2

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 1]],

       [[5, 6],
        [8, 6],
        [7, 4]],

       [[2, 1],
        [5, 3],
        [5, 7]],

       [[5, 2],
        [4, 8],
        [9, 2]]], dtype=int32)>

In [19]:
tensor2.ndim

3

What I've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector) 